### ISSUE TITLE
Mapper

### ISSUE THREAD

**Issue by nyszilard** [turkraft/spring-filter#100]
Is there a way to map properties?

I use DTOs, and on the frontend for example I have:
```
interface ThisDto {
  id: number,
  otherId: number,
  ....
}
```

and on the backend I have:
```
ThisEntity {
  Long id;
  OtherEntity otherEntity;
}

OtherEntity {
  Long id;
  ...
}
```

If I want to use a filter on the otherId, I have to extend my dto with this on the frontend:
```
interface ThisDto {
  id: number,
  otherId: number,
  OtherEntity otherEntity
}

interface OtherEntity {
  id: number
}
```

But it would be much simpler and cleaner if I could configure it, like in the modelMapper:
```
TypeMap<ThisDto, OtherEntity> typeMap = modelMapper.createTypeMap(ThisDto.class, OtherEntity.class);
typeMap.addMappings(mapper -> {
    mapper.map(ThisDto::getOtherId, OtherEntity::setId);
});
```

**Comment by nyszilard** [comment]
Now that I think about it better, I can solve it with a frontend side mapper, so it’s not necessary at all :)

**Comment by torshid** [comment]
I think it's out of the scope of the library. If you are able to do it in the frontend side, that seems fine to me.
