### ISSUE TITLE
Is it possible to work on POST endpoints?

### ISSUE THREAD

**Issue by junhuhdev** [turkraft/spring-filter#102]
Hi is it possible to enable @Filter on POST endpoints?

Reason im asking is because for GET we have care about url encoding, which can make the front-end clients quite verbose for example 

GET http://test.com?page=0&sort=id&filter=ssn:'11111'

Instead we could have 

POST 

```javascript
{
   "query": "ssn: '111' and name: '123'"
}
```

**Comment by torshid** [comment]
Hello,

The library does not support what you are asking for, as a POST request's body may be in many different formats (JSON, XML, plain text, different variable names, etc.).

But you can easily implement that feature yourself:
```java
@PostMapping("/filter")
public Page<Entity> filter(@RequestBody Query query, Pageable page) {
  return repo.findAll(new FilterSpecification<Entity>(query.value), page);
}

class Query {
  String value;
}
```

Hope that was clear.

**Comment by torshid** [comment]
Closing for now. Feel free to reopen if needed.
