### ISSUE TITLE
Support Search in ElementCollection

### ISSUE THREAD

**Issue by moiflo033** [turkraft/spring-filter#124]
It would be nice if you could search for Elements in a collection.

**Comment by torshid** [comment]
I also wanted to know what kind of search you want to do on those collections.

For example
* `collection in ('x', 'y', 'z')` : is one of `x`, `y`, `z` an element of `collection`?
* `collection : 'x'` : is `x` inside `collection`?
* `collection ! 'x'` : is `x` not inside `collection`?

I think that those are what you expect. Correct me if I am wrong please.

**Comment by wicaksono** [comment]
hi @torshid any update on this case?

**Comment by torshid** [comment]
Hey @wicaksono @moiflo033 

Unfortunately I didn't get the time to focus on this issue.
Your contributions are always welcome. You can also [sponsor me](https://github.com/sponsors/torshid) so that I can give better support.

**Comment by Dennis-Nilsson** [comment]
@torshid 
I think I have a solution for the parsing, but I don't know if that is enough. 

I cloned the repository and tried to build a jar to test it locally with `mvn clean install` but I get some error: 
`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-gpg-plugin:3.0.1:sign (sign-artifacts) on project spring-filter: Exit code: 2 -> [Help 1]`

I think this code in the class "StringConverter.java" at row 122 would be something to try out:
```
        if (Map.class.isAssignableFrom(expectedType)) {
            Map<String, String> hashMap = new HashMap<>();
            String keyValues[] = input.split(",");

            for (String keyValue : keyValues) {

                String[] splitKeyValue = keyValue.split(":");

                String key = splitKeyValue[0].trim();
                String value = splitKeyValue[1].trim();

                hashMap.put(key, value);
            }

            if (hashMap.isEmpty()) {
                throw new ClassCastException("The input '" + input + "' could not be parsed to Map");
            }

            return hashMap;
        }
```

Then you should be able to parse a string like this: `'Aashish:1, Bina:2, Chintu:3'`

**Comment by torshid** [comment]
It is now possible to filter `@ElementCollection` (lists and maps) in version 3.0.0.

Consider `map` to be a `Map<?, ?>`, you can query: `map.key : 'test'` and `map.value : 'test'`.
