### ISSUE TITLE
Add support for BigDecimal

### ISSUE THREAD

**Issue by sisimomo** [turkraft/spring-filter#148]
Hi,

I'm just trying to filter entities on a BigDecimal field but I get this error:

`com.turkraft.springfilter.exception.InternalFilterException: The input '5' could not be converted to class java.math.BigDecimal
        at com.turkraft.springfilter.parser.generator.expression.ExpressionGenerator.visitInput(ExpressionGenerator.java:471) ~[spring-filter-2.0.2.jar:na]`

Could you please add support for BigDecimal.

**Comment by torshid** [comment]
Should be fixed in https://github.com/turkraft/spring-filter/releases/tag/2.0.3, feel free to reopen if not. :)
