### ISSUE TITLE
Add support for field with number in them

### ISSUE THREAD

**Issue by sisimomo** [turkraft/spring-filter#149]
Hi,

I'm just trying to filter entities on a fields containing number but I get this error:
`2021-11-03 21:33:48.454 ERROR 19900 --- [nio-8080-exec-5] o.a.c.c.C.[.[.[.[dispatcherServlet]      : Servlet.service() for servlet [dispatcherServlet] in context with path [/sffCasesPartsLists] threw exception [Request processing failed; nested exception is com.turkraft.springfilter.exception.BadFilterSyntaxException: mismatched input '25' expecting {<EOF>, '~', ':', '!', '>', '>:', '<', '<:', AND, OR, IN, IS_NULL, IS_NOT_NULL, IS_EMPTY, IS_NOT_EMPTY, '.'}] with root cause`

I'm using this filter:
`caseInformation.drive25.min >: 2`

So Could you please add support for any valid Java variable name.

Thanks!

By the way thanks for the amazing work on this library!

**Comment by torshid** [comment]
Should be fixed in https://github.com/turkraft/spring-filter/releases/tag/2.0.3, feel free to reopen if not. :)
