### ISSUE TITLE
Support case sensitive operator dinamically

### ISSUE THREAD

**Issue by marcopag90** [turkraft/spring-filter#163]
Hey :) 
I've been very busy lately, couldn't follow the project as I loved to.
Anyway, while working with the library I had to face the problem of building like filters that had to be case sensitive in some circumstances.
The ```FilterParameters.CASE_SENSITIVE_LIKE_OPERATOR``` cannot be changed directly without affecting all the application behaviour, or at least it cannot be done without adding some logic, like a servlet Filter, before passing through the implementation of the ```HandlerMethodArgumentResolver``` that parses the query string and applies the operators, but it's static too, so its logic is shared around, concurrency won't be nice this way.

Maybe another token in the grammar could be useful...I don't know, something like name ~~ 'Mario', where the ~~ stands for the strict sensitive match?

**Comment by torshid** [comment]
Hi :)

I would like to better integrate these parameters to Spring, instead of adding additional syntax. I will see what I can do.

**Comment by torshid** [comment]
Hi @marcopag90 

The `~~` case insensitive like operator was added in version 3.0.0. `~` will always be case sensitive.
