### ISSUE TITLE
Grammar bug ?

### ISSUE THREAD

**Issue by adrianiacobghiula** [turkraft/spring-filter#164]
`maritalStatus or payslips is empty` end up as `( generatedAlias0.maritalStatus = true ) or ( generatedAlias0.payslips = true ) is null`

**Comment by torshid** [comment]
Hi,

Well the input is a bit weird (although valid), which filter are you trying to apply on `maritalStatus`? The behavior may depend on the type of that field. It may have a different meaning if `maritalStatus` is a string, a collection, a boolean, etc.

The bug I guess you spotted here is related to `is empty`, it should have been given priority over `or`.  I would expect something like `( generatedAlias0.maritalStatus = true ) or ( generatedAlias0.payslips is empty )`. Do you agree?

**Comment by adrianiacobghiula** [comment]
Just for the purpose of demo assume `maritalStatus` would be boolean. 

Yes, that would have been the expected output.

**Comment by torshid** [comment]
Correct, will try to fix that tomorrow.

**Comment by torshid** [comment]
I tried your filter with the application provided in the test package, and this is what I get after having set `maritalStatus` to a boolean (as it is an enum in the app) for `maritalStatus or payslips is empty`:
```sql
    where
        employee0_.marital_status=1 
        or  not (exists (select
            payslips1_.id 
        from
            payslip payslips1_ 
        where
            employee0_.id=payslips1_.employee_id))
```

It seems that there is no problem, what do you think?

**Comment by adrianiacobghiula** [comment]
Looks ok

**Comment by torshid** [comment]
Closing the issue then, if you encounter something similar you can always reopen the issue.
