### ISSUE TITLE
Swagger

### ISSUE THREAD

**Issue by muhdkhokhar** [turkraft/spring-filter#177]
Will it also work in sWAGGER?
Can user test out in swagger?

**Comment by torshid** [comment]
I am not sure what you mean by that question. If you are asking about the Swagger generation of the API (using springdoc or springfox), then you can simply use the `@Parameter` annotation to customize the documentation:
```java
List<Entity> listEntities(@Parameter(in = ParameterIn.QUERY, name = "filter", description = "Filter query", schema = @Schema(type = "string")) @Filter Specification<Entity> spec) {
 // ...
}
```

It will do something similar to:
![image](https://user-images.githubusercontent.com/977909/146791171-c9a48989-7034-4b37-961d-6f6fd4604427.png)

**Comment by muhdkhokhar** [comment]
thanks exactly I was looking for that.
