### ISSUE TITLE
Support for Security Expression

### ISSUE THREAD

**Issue by vittoN** [turkraft/spring-filter#207]
Thanks for this good library!
It would be great to have support for security expressions similarly to Spring in @Query (https://docs.spring.io/spring-security/site/docs/4.0.1.RELEASE/reference/htmlsingle/#data).

**Comment by torshid** [comment]
Hey @vittoN :)
I am not sure if I have understood correctly your suggestion, can you give an example of how would you use that in a filter query?

**Comment by vittoN** [comment]
Let's assume i would extract all messages where recipient is the user logged in the system. So, using a custom JPA query i'll write:
	
	@Query("select m from Message m where m.to.id = ?#{ principal?.id }")
	Page<Message> findInbox(Pageable pageable);
	
I would like a way to limit searched results in the same way using spring-filter.

**Comment by torshid** [comment]
I see what you mean, I think it will be quiet hard to support `@Query`. What you can do is anding the user's filter with an another filter:

```java
Specification<Message> incomingFilter = // user's filter

Specification<Message> loggedInUserFilter = new FilterSpecification<Message>(FilterBuilder.equal("principal.id", getLoggedInUserId()));

Specification<Message> finalFilter = FilterSpecification.merge(incomingFilter, loggedInUserFilter); // or Specification.where(loggedInUserFilter).and(incomingFilter);

Page<Message> messages = repository.findAll(finalFilter, pageable);
```

Hope it's clear.

**Comment by torshid** [comment]
@vittoN I think that anding filters should have met your requirements, closing the issue for now.
