### ISSUE TITLE
Support filter for AttributeConverter fields

### ISSUE THREAD

**Issue by MonuChandramohan** [turkraft/spring-filter#218]
It would be nice have filter functionality on filelds which uses attributeconvertor.

I have a convertor class

`public class MasterAttributeConvertor implements AttributeConverter<TestEntity, Integer> { `     

`private final RedisAdaptor<Integer, TestCacheEntity> masterModelCacheAdaptor;`

`  @Override
  public Integer convertToDatabaseColumn(){}`

` public MasterCacheEntity convertToEntityAttribute(Integer testId) (){}`

using redis, this converts 

id to TestEntiy when giving as response.
converts TestEntity to id when saving in db.

Right now if I pass testId to filter the convertor field. it would throw "**cannot cast integer to testCacheEntity**"

**Comment by torshid** [comment]
Hi @MonuChandramohan,

Not sure why you closed the issue, but you should be able to do it with the `JAVA_TYPE_MODIFIER ` parameter (please see notes for https://github.com/turkraft/spring-filter/releases/tag/2.0.7).

**Comment by MonuChandramohan** [comment]
Hi @torshid.

I can able to search the convertor object. which is converted from redis using attributeConvertor in spring.

Working fine now. So closed it.

Anyway thanks for the quick response.
