### ISSUE TITLE
MongoDB usage example

### ISSUE THREAD

**Issue by phyolim** [turkraft/spring-filter#226]
Could someone post a usage with MongoDB? I've looking everywhere but, not able to find any example.
I saw the example with MongoDB in readme, but, wasn't sure what to do with the following part.

```
Bson bson = BsonGenerator.run(Filter.from(query), Entity.class);
Document doc = BsonUtils.getDocumentFromBson(bson);
Query query = BsonUtils.getQueryFromDocument(doc);
// ...
```

**Comment by phyolim** [comment]
I think I figured out..

Needed to define a CustomRepository and Implementation and use        
`Query query = BsonGeneratorUtils.getQueryFromDocument(doc);`

to get query from Url. 

Then do `mongoTemplate.find(query, Order.class);`

**Comment by torshid** [comment]
Hey @phyolim, you can do it as you wrote with `mongoTemplate.find(query, Order.class)`, or your repository may implement the `DocumentExecutor` interface and you can then do `repo.findAll(doc)`.
