### ISSUE TITLE
Sharing instance of NumberFormat can cause diffrent results

### ISSUE THREAD

**Issue by capussopy** [turkraft/spring-filter#227]
When parallel requests are sent via filter, the sharing `NumberFormat` instance parse randomly different numbers. Sometimes it fails , sometime its correct and sometimes it parses a double out.

The issue is caused by your `StringConverter.class`

An simple example that causes the issue:

```
public class Scratch extends Thread {

    public static final NumberFormat NUMBER_FORMAT ;

    public static void main(String args[]) {
        for (int i = 0; i < 3; i++) {
            Scratch thread = new Scratch();
            thread.start();
        }
    }

    public void run() {
        ParsePosition position = new ParsePosition(0);
        Number number = NUMBER_FORMAT.parse("1011", position);
        System.out.println(number);
    }

    static {
        NUMBER_FORMAT = NumberFormat.getInstance(Locale.US);
        NUMBER_FORMAT.setGroupingUsed(false);
    }
}
```

The issue disapers, if we use a new instance of Numberformat in every Thread:

```
public class Scratch extends Thread {


    public static void main(String args[]) {
        for (int i = 0; i < 5; i++) {
            Scratch thread = new Scratch();
            thread.start();
        }
    }

    public void run() {
        ParsePosition position = new ParsePosition(0);
        NumberFormat format = NumberFormat.getInstance(Locale.US);
        format.setGroupingUsed(false);
        Number number = format.parse("1011", position);
        System.out.println(number);
    }
  
}
```

**Comment by torshid** [comment]
@capussopy Thanks for noticing about this. I think that we have a similar issue with `SimpleDateFormat`, which is not thread safe too. It should be possible to wrap these fields with `ThreadLocal`, do you have other solutions?

**Comment by capussopy** [comment]
@torshid This is true. The Javadoc for `SimpleDateFormat` says: 

> Date formats are not synchronized. It is recommended to create separate format instances for each thread. If multiple threads access a format concurrently, it must be synchronized externally.

yes, you can use `Threadlocal` or create a new instance in each thread. I think the solution with ThreadLocal should have the better performance. But im not 100% sure.

**Comment by capussopy** [comment]
@torshid any updates on this?

**Comment by FelipeBerrios** [comment]
any updates?

**Comment by torshid** [comment]
Fixed in https://github.com/turkraft/spring-filter/releases/tag/2.1.2.

**Comment by FlorianCassayre** [comment]
@skamv
