### ISSUE TITLE
No primary or default constructor found for interface org.springframework.data.jpa.domain.Specification.How to solve it?

### ISSUE THREAD

**Issue by VS-88** [turkraft/spring-filter#229]
Hi!

I have problem while integrating this library with my project (Spring boot 2.7.2, Spring Data Rest (last stable)).
I need to write custom controller for search logic but with all of advantages of the Spring Data Rest library and this library, so I used @RepositoryRestController annotation - and as a result I got error "No primary or default constructor found for interface org.springframework.data.jpa.domain.Specification".
Signature of Controller method looks like the example https://github.com/turkraft/spring-filter : 

@RequestMapping(method = RequestMethod.GET, value = "/someUrl")
public @ResponseBody ResponseEntity search(@Filter Specification specification);

Will be grateful for any idea!

**Comment by torshid** [comment]
Hi @VS-88
Do you get the same error when using the following?
```java
public @responsebody ResponseEntity search(FilterSpecification<T> specification);
```

**Comment by VS-88** [comment]
> Hi @VS-88 Do you get the same error when using the following?
> 
> ```java
> public @responsebody ResponseEntity search(FilterSpecification<T> specification);
> ```

Hi!

Thank you for reply!

But the issue is the same:  java.lang.IllegalStateException: No primary or single unique constructor found for class com.turkraft.springfilter.boot.FilterSpecification

**Comment by torshid** [comment]
Hello @VS-88,

I think that this should do the job:

```java
@RepositoryRestResource
public interface MyRepo extends JpaRepository<T, Long>, JpaSpecificationExecutor<T> {

  @ResponseBody
  default ResponseEntity<List<T>> search(@Filter Specification<T> specification) {
    return ResponseEntity.ok(findAll(specification));
  }

  @ResponseBody
  default ResponseEntity<T> searchOne(@Filter Specification<T> specification) {
    return ResponseEntity.ok(findOne(specification).orElseThrow(new NotFoundException()));
  }

}
```

Feel free to reopen the issue if it's not working as expected. Also do note that this is more a Spring related issue, you can always [support me](https://github.com/sponsors/torshid) to be prioritized over other pending issues.

Thank you.

**Comment by akbartrinanda** [comment]
> Hello @VS-88,
> 
> I think that this should do the job:
> 
> ```java
> @RepositoryRestResource
> public interface MyRepo extends JpaRepository<T, Long>, JpaSpecificationExecutor<T> {
> 
>   @ResponseBody
>   default ResponseEntity<List<T>> search(@Filter Specification<T> specification) {
>     return ResponseEntity.ok(findAll(specification));
>   }
> 
>   @ResponseBody
>   default ResponseEntity<T> searchOne(@Filter Specification<T> specification) {
>     return ResponseEntity.ok(findOne(specification).orElseThrow(new NotFoundException()));
>   }
> 
> }
> ```
> 
> Feel free to reopen the issue if it's not working as expected. Also do note that this is more a Spring related issue, you can always [support me](https://github.com/sponsors/torshid) to be prioritized over other pending issues.
> 
> Thank you.

**Comment by torshid** [comment]
Hi @akbartrinanda 

Can you share your code?

**Comment by akbartrinanda** [comment]
Hello @torshid 
This is my code:

```
public interface UserRepository extends JpaRepository<User, String>, JpaSpecificationExecutor<User> {

	@ResponseBody
	default ResponseEntity<List<User>> search(@Filter Specification<User> specification) {
		return ResponseEntity.ok(findAll(specification));
	}

	@ResponseBody
	default ResponseEntity<User> searchOne(@Filter Specification<User> specification) {
		return ResponseEntity.ok(findOne(specification).orElse(null));
	}

}
```

```
@GetMapping(value = "/search")
public ResponseEntity<List<User>> search(@Filter Specification<User> spec) {
    return userRepository.search(spec);
}
```

This is the response:

> {
    "title": "Internal Server Error",
    "status": 500,
    "detail": "No primary or single unique constructor found for interface org.springframework.data.jpa.domain.Specification"
}

**Comment by torshid** [comment]
Can you extend SimpleJpaRepository in your repository and check if you still get an error?

**Comment by akbartrinanda** [comment]
> Can you extend SimpleJpaRepository in your repository and check if you still get an error?

@torshid hello, can u help me ?

**Comment by torshid** [comment]
I am not sure why you are getting this error... Can you check the `jpa-example` project?
