### ISSUE TITLE
ZonedDateTime support

### ISSUE THREAD

**Issue by Fejiro-A** [turkraft/spring-filter#246]
Please would it be possible to add support for filtering fields with ZonedDateTime? Or Is there some bean that can be exposed so that we can implement our own type conversions?

**Comment by sisimomo** [comment]
Unfortunately, there is no way to provide your own type converter. But if it's a class from a mainstream package, you can just make a small pull request with the necessary code modifications. I did this recently to add class support for "java.time.OffsetTime", "java.time.YearMonth", "java.time.MonthDay".

If you look at the pull request I made, you'll see all the places where you need to add code.
https://github.com/turkraft/spring-filter/pull/245/files

**Comment by torshid** [comment]
Hi @Fejiro-A,

ZonedDateTime is now supported in release 3.0.0.
