### ISSUE TITLE
Is there a way to ignore special characters when comparing strings?

### ISSUE THREAD

**Issue by FelipeBerrios** [turkraft/spring-filter#250]
We are developing an application where there are special characters like 

> ñ ´
 
Is there a way to use the like matcher ignoring these characters?

Thank you

**Comment by torshid** [comment]
Hi @FelipeBerrios,

Since the implementation is platform-dependent it can't be done in this codebase directly.
I am not sure which database you are using but you should consider creating a custom function which would do the job.
