### ISSUE TITLE
Custom filter

### ISSUE THREAD

**Issue by MiguelAngelLV** [turkraft/spring-filter#251]
I think that we need add customs filter.

Maybe you can set the field and operator and lambda to realize the operation

```
val filter = FilterSpecificationCustom<Entity>(query)
filter.custom("myfield", "$")  { criteria, value ->

//Create custom criteria
}

val specification = filter.build()

```

**Comment by torshid** [comment]
Hi @MiguelAngelLV 

This is now possible in version 3.0.0.

**Comment by MiguelAngelLV** [comment]
Perfect. Thanks you
