### ISSUE TITLE
Spring Filter for Spring Boot 3.x.x : Compatability issue with spring-data-rest

### ISSUE THREAD

**Issue by ddewaele** [turkraft/spring-filter#261]
When the library is used with a project that includes `spring-data-rest`. it fails to start due to the following error : 

This is because `spring-data-rest` also registers its own `ConversionService`

Using `@Qualifier("mvcConversionService")` should fix it.

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of constructor in com.turkraft.springfilter.converter.FilterSpecificationConverterImpl required a single bean, but 2 were found:
	- mvcConversionService: defined by method 'mvcConversionService' in class path resource [org/springframework/boot/autoconfigure/web/servlet/WebMvcAutoConfiguration$EnableWebMvcConfiguration.class]
	- defaultConversionService: defined by method 'defaultConversionService' in class path resource [org/springframework/data/rest/webmvc/config/RepositoryRestMvcConfiguration.class]


Action:

Consider marking one of the beans as @Primary, updating the consumer to accept multiple beans, or using @Qualifier to identify the bean that should be consumed
```

**Comment by torshid** [comment]
Hi @ddewaele 

Using `@Qualifier("mvcConversionService")` would be problematic for projects not using `spring-data-rest` I guess. The service is injected in several places too, a solution without using a qualifier would be better. Not sure how it can be done though.
It is possible to define one of the beans as primary on your side but we should provide a better a solution.

Any ideas?

**Comment by torshid** [comment]
Proposing another solution: what about using a qualifier such as `@Qualifier("springfilterConversionService")` where the specified bean would automatically point to a valid implementation (via a configuration class)?

**Comment by ddewaele** [comment]
That's also possible. 

Although `mvcConversionService` is part of the plain vanilla `spring-webmvc` and will always be present. (I guess your library has a dependency with spring-webmvc and expects it to be present.)

Just tested it with and without the `spring-data-rest` dependency.

**Comment by ddewaele** [comment]
Not really sure if there is a good way to "wrap" existing beans without getting into unresolvable circular references.

If your library has a dependency with spring-web, injecting the `mvcConversionService` might be the only option.

I've setup a sponsorship for you through my company Ixor ... we're using the library across several projects and are now upgrading a large part of those projects to Spring Boot 3.x

So hopefully we'll be able to provide some good feedback

**Comment by torshid** [comment]
Hello @ddewaele 

Thank you for sponsoring the project.

The library does not depend on spring-web as it may me used in non-web applications. I will try to implement a solution and release a snapshot today.

I look forward to hearing your feedbacks.

**Comment by ddewaele** [comment]
No worries. Happy to help.

I was ondering about that dependency because I did notice some `org.springframework.web` compile-time dependencies in the code.

Would be great if you could somehow also publish the 3.0.0-SNAPSHOT to a public repo like you did with the previous releases

**Comment by ddewaele** [comment]
Should be possible to create a more fancy version of this with some conditional beans depending on what dependencies you have in the project

```
@Configuration
public class SpringFilterConversionConfig {

    @Bean
    public ConversionService springFilterConversionService(ConversionService conversionService) {
        return conversionService;
    }
}
```

**Comment by ddewaele** [comment]
FYI, 

```
<dependency>
   <groupId>org.springframework.cloud</groupId>
   <artifactId>spring-cloud-starter-openfeign</artifactId>
</dependency>
```

Is another one of those starters that registers its own `ConversionService`

```
Parameter 0 of constructor in com.turkraft.springfilter.converter.FilterSpecificationConverterImpl required a single bean, but 3 were found:
	- mvcConversionService: defined by method 'mvcConversionService' in class path resource [org/springframework/boot/autoconfigure/web/servlet/WebMvcAutoConfiguration$EnableWebMvcConfiguration.class]
	- feignConversionService: defined by method 'feignConversionService' in class path resource [org/springframework/cloud/openfeign/FeignClientsConfiguration.class]
	- defaultConversionService: defined by method 'defaultConversionService' in class path resource [org/springframework/data/rest/webmvc/config/RepositoryRestMvcConfiguration.class]
```

**Comment by torshid** [comment]
Here is the fix https://github.com/turkraft/spring-filter/commit/5e45bc936fc810015cf9a749ae5520bfb8797918, that should to the work for now.

You can try using https://github.com/turkraft/spring-filter/releases/tag/3.0.1-SNAPSHOT.

```xml
<dependency>
  <groupId>com.turkraft.springfilter</groupId>
  <artifactId>jpa</artifactId>
  <version>3.0.1-SNAPSHOT</version>
</dependency>
```

Do not forget to add the snapshot repository to your POM:
```xml
<repositories>
  <repository>
    <id>oss.sonatype.org-snapshot</id>
    <url>https://oss.sonatype.org/content/repositories/snapshots</url>
    <releases>
      <enabled>false</enabled>
    </releases>
    <snapshots>
      <enabled>true</enabled>
    </snapshots>
  </repository>
</repositories>
```

**Comment by ddewaele** [comment]
Getting similar error. Related to the `ConverterRegistry` injection

```
Parameter 2 of constructor in com.turkraft.springfilter.boot.FilterConversionServiceConfiguration required a single bean, but 3 were found:
	- mvcConversionService: defined by method 'mvcConversionService' in class path resource [org/springframework/boot/autoconfigure/web/servlet/WebMvcAutoConfiguration$EnableWebMvcConfiguration.class]
	- feignConversionService: defined by method 'feignConversionService' in class path resource [org/springframework/cloud/openfeign/FeignClientsConfiguration.class]
	- defaultConversionService: defined by method 'defaultConversionService' in class path resource [org/springframework/data/rest/webmvc/config/RepositoryRestMvcConfiguration.class]
```

If I run a test with the library and try to inject a `ConverterRegistry` I get 4 matching beans : 

```
No qualifying bean of type 'org.springframework.core.convert.converter.ConverterRegistry' available: expected single matching bean but found 4: conversionService,converterRegistry,mvcConversionService,defaultConversionService
```

That's because all of the `ConversionService` beans that are created by Spring are also `ConverterRegistry` beans

for example: 
```
public class FormattingConversionService extends GenericConversionService
		implements FormatterRegistry, EmbeddedValueResolverAware {
```

**Comment by torshid** [comment]
I missed that when playing with dependencies.

Can you try again with https://github.com/turkraft/spring-filter/releases/tag/3.0.2-SNAPSHOT?

Thanks.

**Comment by ddewaele** [comment]
App starts fine. Will continue testing tomorrow !

Thx !

**Comment by ddewaele** [comment]
Would it be possible to create a release for the 3.0.2-SNAPSHOT ?

**Comment by ddewaele** [comment]
yes, but I meant a 3.0.2 release (not a snapshot).

Our build policies don't allow for snapshot deployments.

**Comment by torshid** [comment]
Oh I see but there are still a few things I would like to complete before taking the 3.x.x branch to the main one and making an official release.

**Comment by ddewaele** [comment]
Do you have an ETA on this ? Need to provide a plan for our testers.
