### ISSUE TITLE
Mongo not working without webmvc?

### ISSUE THREAD

**Issue by diogoafg13** [turkraft/spring-filter#285]
Hi,
First of all congratulations on the library, it seems to have a lot of potential. I'm planning to use this lib but I'm facing a problem.

I have this example code:

`
@Operation(
      parameters =
          @Parameter(
              name = "filter",
              in = ParameterIn.QUERY,
              schema = @Schema(type = "string"),
              example = "employee.salary > 3000"))
  @PutMapping(
      value = "/v1/example",
      produces = {
        "application/json",
      })
  Flux<ExampleDto> getExample(
      @Filter(entityClass = ExampleDto.class) Document filter) {
return Flux.from(exampleService.getExamples(filter));
  }
`

I've added this dependency 

`
<dependency>
	<groupId>com.turkraft.springfilter</groupId>
	<artifactId>mongo</artifactId>
	<version>3.0.7</version>
</dependency>
`

In order to have it working I need to add to the pom.xml this dependency
`
<dependency>
 <groupId>org.springframework.boot</groupId>
 <artifactId>spring-boot-starter-web</artifactId>
</dependency>
`

It works fine but since I want my web application as reactive, when I add this property to my application.yml

`
spring:
  main.web-application-type: REACTIVE
` 

It doesn't work anymore, filter is empty. I need to add this property since I have now web mvc and webflux and I want my application to be of type Reactive. I guess filter only works with Web Mvc.

Is there a workaround to use reactive with this library or are you planning to support reactive?

**Comment by torshid** [comment]
Hi @diogoafg13 

What error do you get when webmvc is not present in your dependencies?

**Comment by torshid** [comment]
I think that without webmvc the controller can't handle the `Document` argument, right?

You may take a string input, and transform it to a `Document` manually:

```java

@Autowired
FilterStringConverter filterStringConverter;

@Autowired
FilterJsonNodeTransformer filterJsonNodeTransformer;

@Autowired
JsonNodeHelper jsonNodeHelper;

ResponseEntity<> endpoint(String filter) {
  ObjectNode jsonResult = jsonNodeHelper.wrapWithMongoExpression(filterJsonNodeTransformer.transform(filterStringConverter.convert(filter))));
  Document document = Document.parse(jsonResult.toString());
}
```

You may check the `FilterJsonNodeArgumentResolver` class to see how it's done more precisely.

**Comment by diogoafg13** [comment]
> I think that without webmvc the controller can't handle the `Document` argument, right?
> 
> You may take a string input, and transform it to a `Document` manually:
> 
> ```java
> @Autowired
> FilterStringConverter filterStringConverter;
> 
> @Autowired
> FilterJsonNodeTransformer filterJsonNodeTransformer;
> 
> @Autowired
> JsonNodeHelper jsonNodeHelper;
> 
> ResponseEntity<> endpoint(String filter) {
>   ObjectNode jsonResult = jsonNodeHelper.wrapWithMongoExpression(filterJsonNodeTransformer.transform(filterStringConverter.convert(filter))));
>   Document document = Document.parse(jsonResult.toString());
> }
> ```
> 
> You may check the `FilterJsonNodeArgumentResolver` class to see how it's done more precisely.

Thanks for your quick response.
I followed your approach and it is working now. For anyone with the same problem. I had to create the following config in order to have it working since I had multiple beans (sfConversionService and webFluxConversionService in my case).


```java
@Configuration
public class SpringFilterConfig {

  private final ConversionService conversionService;

  private final ObjectMapper objectMapper;

  private final FilterNodeProcessorFactories filterNodeProcessorFactories;

  @Autowired
  public SpringFilterConfig(@Qualifier("sfConversionService") ConversionService conversionService,
      ObjectMapper objectMapper, FilterNodeProcessorFactories filterNodeProcessorFactories) {
    this.conversionService = conversionService;
    this.objectMapper = objectMapper;
    this.filterNodeProcessorFactories = filterNodeProcessorFactories;
  }

  @Bean
  FilterJsonNodeTransformer filterJsonNodeTransformer() {
    return new FilterJsonNodeTransformer(
        conversionService, objectMapper, filterNodeProcessorFactories, ExampleDto.class);
  }
}
```

Keep up the awesome work and thanks again 👍

**Comment by torshid** [comment]
Thanks for sharing the code!
