### ISSUE TITLE
Functions with expressions

### ISSUE THREAD

**Issue by marcopag90** [turkraft/spring-filter#55]
is there a way to provide a function whose result is the computation of an expression?
eg:
/car?filter=size(wheels.diameter>:10)>3
which means "find every car with at least 4 wheels with a diameter >=10".

**Comment by torshid** [comment]
That's an interesting use case. You can't do that with the `size` function as JPA expects a collection expression and you are providing a predicate (bool) expression. There is actually a subquery going on here, not sure how to handle it. The CriteriaBuilder's `count` method may be used somehow, I will try to think about it. Feel free to contribute (the class handling functions is not very well written, sorry for that).
https://github.com/turkraft/spring-filter/blob/2ff8818899341b10f2f2ac583a93e1f3bacfec05/src/main/java/com/turkraft/springfilter/node/Function.java#L104-L105

**Comment by torshid** [comment]
I just read the issue again, and the statement `find every car with at least 4 wheels with a diameter >=10` should be equivalent to `/car?filter=size(wheels) >: 4 wheels.diameter >: 10`.

Not sure it completely solves the issue though.

**Comment by torshid** [comment]
I have added support for the [exists](https://github.com/turkraft/spring-filter#subqueries) function. It may possibly answer this issue.

Closing for now.
