### ISSUE TITLE
Please help with 'NOT LIKE' case

### ISSUE THREAD

**Issue by nabildridi** [turkraft/spring-filter#58]
Please how to do a 'not like' filter?
I wanted to do 'not contains' filter (in SQl it's NOT LIKE '%value%') but I failed, I tested many formulas :

- !'%value%'
- !~'%value%'
- not(~'%value%')

But it didn't work.
Thank you.

**Comment by torshid** [comment]
You can do it with `not (field ~ '%value%')`, parentheses are optional. You may also do it with `field not ~ '%value%'`.

It will generate the following statement:
```sql
where upper(field) not like ? -- [%VALUE%]
```

Note that `!` is the `not equal` comparator (inverse of `:`), it is not the `not` binary operator.
