### ISSUE TITLE
MongoDB date fields support

### ISSUE THREAD

**Issue by marcopag90** [turkraft/spring-filter#62]
Ok so, I'm opening this issue for further investigations over the ability to query a date field via MongoRepository.

I've found this project to start from:
https://github.com/RutledgePaulV/rsql-mongodb

This is using the Visitor pattern. 
A bit different, but same result. Maybe it could be inspiring.

**Comment by torshid** [comment]
Just taking some notes:
* https://github.com/RutledgePaulV/rsql-mongodb/blob/29f5b6dd087ef55583839c71def1d2eb3164c40a/src/main/java/com/rutledgepaulv/github/argconverters/EntityFieldTypeConverter.java: PersistentPropertyPath/MongoMappingContext is used to determine field types
* https://github.com/RutledgePaulV/rest-query-engine/blob/develop/src/main/java/com/github/rutledgepaulv/rqe/resolvers/EntityFieldTypeResolver.java: generic way using reflection (with `org.apache.commons.lang3.reflect.FieldUtils` as a dependency)

Not sure with which one to go for now.

**Comment by torshid** [comment]
@marcopag90 @glodepa dates are now supported in https://github.com/turkraft/spring-filter/releases/tag/1.0.4. However be careful with the [date formats](https://github.com/turkraft/spring-filter#date-format).

I am waiting for your feedback before closing this issue.

**Comment by torshid** [comment]
Any news here?

**Comment by marcopag90** [comment]
Yep, so far we successfully tested LocalDate, LocalDateTime and Instant queries.
Other date tests incoming soon :)

**Comment by torshid** [comment]
Excellent, closing this then. You may open another issue if you encounter any problem.
