### ISSUE TITLE
Like Case-sensitive

### ISSUE THREAD

**Issue by marcopag90** [turkraft/spring-filter#70]
I'm opening this issue to discuss about a **like** operator supporting **case sensitive** function.
Sometimes it could be useful to provide a like query which matches exactly with the case provided.
Tell me what do you think about it!

**Comment by torshid** [comment]
Not sure how to provide this feature.

As an operator (which symbol?), as a function? We can maybe put a flag in the config class and let the user decide the general behavior?

We may also not interfer at all, and directly call JPA's like function without applying uppercase as it is now. The user may then use a query as follows for case insensitive searches but it adds some complexity: `uppercase(name) ~ '%DOE%'`

**Comment by marcopag90** [comment]
Mmh, general behaviour could not be the case, there are scenario where I'd rather prefer to perform a query as if i'm considering a function. 
Maybe the uppercase function is the right way, so without interfering at all in JPA.
What about adding another token operator (if the grammar allows it) such as **~i** '%DOE%'? This could means insensitive, while default **i** is just as if the query was seen from a database perspective?

**Comment by torshid** [comment]
Not interfering with JPA looks like the best option.
Adding another operator means that it should also be implemented in MongoDB (and maybe other things to come) and it may not make sense in some cases. On top of that it opens too many doors which can easily complexify the current query syntax.

What I'll do is:
* Keep the current case insensitive behavior
* Add a config flag to disable this default behavior
* Add the uppercase function and some others

The query example I gave earlier could then be used to make a case insensitive search in case the default behavior is disabled.

**Comment by marcopag90** [comment]
Ok, seems good to me as well!
