### ISSUE TITLE
UUID and OffsetDateTime support

### ISSUE THREAD

**Issue by petka5** [turkraft/spring-filter#71]
Hi, 
I'm trying to integrate your library into one of my projects.
Since my base JPA entity has a PK UUID, and @UpdateTimestamp  @CreationTimestamp declared as OffsetDateTime
I could find a way to search for them.
Could you please give me some hints.
Best Regards.

**Comment by torshid** [comment]
Hello 👋 

If I understand correctly, you couldn't apply filtering to a field of type OffsetDateTime, am I right? The PK or the annotations are not related to the problem I think.

**Comment by petka5** [comment]
Yes, I have UUID and OffsetDateTime in my entity, and I could manage to apply filter on these two fields.

**Comment by torshid** [comment]
These types are currently not supported but that's quite easy to implement. I will try to do it today.

**Comment by torshid** [comment]
I just released https://github.com/turkraft/spring-filter/releases/tag/1.0.1. `UUID` and `java.time.*` types are now supported with JPA.

Feel free to ask for other field types. :)

**Comment by petka5** [comment]
Great, it works. 
I have few more use-cases in my mind, I could share them with you if you would like.

**Comment by torshid** [comment]
I would appreciate if you can share those. If they are enough generic/common I will try to implement them.
