### ISSUE TITLE
Global filters of all/selected fields

### ISSUE THREAD

**Issue by albertodiazsaez** [turkraft/spring-filter#74]
If I have two or more fields, be able to search in all of them at the same time (or in the selected fields).

My problem is the next one: You have a table with Names and Surnames in two Columns (or paramters in the returned object):

NAME         SURNAME

JOHN         DOE
JOHN         SMITH
PAMELA    DOE
PAMELA    SMITH

Now if I search "Smith", with AND/OR operators, the result will be "John Smith, Pamela Smith", but if I want to be more specific and I search "John%Smith", (name~'John%Smith' AND surname~'John%Smith') the result will be all of them, so the results are worst as more parameters I search, because more words can appear on those fields.

In my proposition, I think something about: "globalFilter:name,surname~'John%Smith'" only the "John Smith will be returned, as it is the only one which contains the search term in the parameters selected.

I don't know if I explained myself enough, english is not my native language. 

Your project has made me want to build APIs again with Spring, It's wonderful and this is the only think that I really missed, I hope it's possible to code... Thank you!

**Comment by torshid** [comment]
Thanks for participating. :)

Just wondering, isn't it possible in this case to search with `firstName : 'John' and lastName : 'Smith'`? Not sure what is the advantage of using `~` here.

I can be more helpful if you can give more details about your use case.

Your globalFilter proposition seems too complex to implement for this specific case. But I think that string concatenation might be useful here, it would be possible to do things like `concat(firstName, concat(' ', lastName)) ~ 'John%Smith'`. The `concat` function isn't implemented currently but that can be easily done.

**Comment by torshid** [comment]
You may check https://github.com/turkraft/spring-filter/releases/tag/1.0.2. I think that you will be now be able to do your search with what I described earlier. If not, you can always reopen the issue or create a new one.

**Comment by albertodiazsaez** [comment]
The concatenation should work. I forgot completely to tell why I need this... >.<

I have a fontend table, and multiple columns, and if I want to use a single search field to search in multiple columns (name/surname/phone/etc), the globalFilter is very useful. The idea is that I can't identify what is going to be on that field, that's why I can't use `firstName : 'John' and lastName : 'Smith'`, but `concat(firstName, concat(' ', lastName)) ~ 'John%Smith'` should work.

To simplify the syntax, I suggest doing a `concat(firstName, ' ', lastName, etc)~'John%Smith' if it's possible, so we don't have to write concat a lot and keep everyhting in the same parenthesis, just a juggestion though.

The concat would be only for filtering right? It's not going to modify the data that it's being returned?

Thank you!

**Comment by torshid** [comment]
I understand now. I assume that you have a single column which combines the first and last names in your frontend, and you want a single search field for that column. The `concat` usage is the most suitable which comes to my mind.

And you are right, the data is absolutely not modified here, the functions and all the operators are only used for the filtering logic. So the `concat` method should not cause any problem. You may modify the data once you fetch it if that's needed.

By the way, what are you using in your frontend? I am planning to build a JS/TS query builder when I have time, it would be interesting to get your requirements.

**Comment by albertodiazsaez** [comment]
The concat operator should be perfect for my use case ^·^

I'm using Angular with TS for my frontend, more specifically, the Prime NG library (Primefaces version for Angular), but the client should be generic enough to be used in Angular, React, so I would suggest doing it on JS.

**Comment by torshid** [comment]
Great. Thank you :)
