### ISSUE TITLE
Date pattern improvment

### ISSUE THREAD

**Issue by Jeffster2021** [turkraft/spring-filter#78]
Hey!

Entity class can map Db field of timestamp format to Date field.
It would be great to have the possibility to filter by that kind of field not only by date but by date and time both.
So for such cases, it would be needed to set the Date pattern as dd-MM-yyyy'T'HH:mm:ss.

Could you improve this?
Thanks.

**Comment by torshid** [comment]
Hello,

Not sure to have understood you but I think that you want to change date patterns. You may check this section of the readme to do that https://github.com/turkraft/spring-filter#date-format.

Or are you asking for Date fields to support multiple patterns at the same time?

**Comment by Jeffster2021** [comment]
I'm asking to support a pattern containing time for Date fields. Or maybe support multiple patterns.

For example, we have a Postgres table
create table test(date_field timestamp);
So field contains date and time.

But the model entity is 

@Entity
class Test {
     private Date dateField;
     ...
}

In this case, we can filter only by date value not considering the time.
Of course, it's possible to change a field in a model entity, but sometimes there are a lot of legacy code :)

**Comment by torshid** [comment]
In your application.properties, if you add
```ini
turkraft.springfilter.dateformatter.pattern=dd-MM-yyyy'T'HH:mm:ss
```
You should be able to filter using `dateField : '12-05-2021T10:39:16'`

**Comment by Jeffster2021** [comment]
Thanks, you're a lifesaver.
I've read the doc page and tried it before, but maybe I was doing something wrong.
Sorry for wasting your time,

**Comment by torshid** [comment]
No problem. Feel free to open other issues.
