### ISSUE TITLE
ReadME does not mention about ExpressionGeneratorParameters

### ISSUE THREAD

**Issue by anmol1vw13** [turkraft/spring-filter#79]
For like queries, the value for CASE_SENSITIVE_LIKE_OPERATOR is false by default, which generated queries like
```
select * from users where upper(name) like "a%";
```
Having an upper function prohibits the query from using indexes and slows the query considerably. I had to set CASE_SENSITIVE_LIKE_OPERATOR as true to stop the query from using the upper function and make use of the indexes I had defined.

```
ExpressionGeneratorParameters.CASE_SENSITIVE_LIKE_OPERATOR = true
```

Can I know the rationale behind having it as false by default?

**Comment by torshid** [comment]
Hello,
The reason for that default value was to no cause breaking changes as uppercasing was always done earlier, because in general that's how people would expect things to be by default I think (case insensitive search).

**Comment by torshid** [comment]
However, you are right, that should be mentionned in the readme, I am going to do it ASAP.
