### ISSUE TITLE
JavaScript Query Builder

### ISSUE THREAD

**Issue by torshid** [turkraft/spring-filter#80]
Hi everyone 👋

I am planning to create a JavaScript filter builder which I think will be helpful when calling APIs with frontend frameworks such as Vue or Angular. It should be similar to the `FilterBuilder` class.

Example:

```js
// lastName : 'Doe' and birthDate > '1-01-2000'
const filter =
    and(
        equal('lastName', 'Doe'),
        greaterThan('birthDate', '1-01-2000')
    ).generate();

const req = await fetch('http://api/person?filter=' + filter);
```

Let me know if you're interested, if you have suggestions or things you would like to see. :)

Edit: we now have our builder https://github.com/sisimomo/Spring-Filter-Query-Builder!

**Comment by marcopag90** [comment]
Well, bread is done....we are just missing butter.
I'm into it. 
This way the library can provide a full stack language.

**Comment by torshid** [comment]
That's an excellent news. :)
Much appreciated. Feel free to discuss as always.

**Comment by sisimomo** [comment]
Hi,

I would love to get something like this. I am working on a website that would need to generate a complex query based on multiple filters from a table (DataTables). I was planning on making a little genetator just to be able to run my business, but if you do a full JavaScript implementation, I'd love to try it out and contribute!

Thank you!

**Comment by torshid** [comment]
Hey,

I didn't get the opportunity to do this unfortunately, I was a bit relying on @marcopag90 to be honest. :)
Not sure how to deal with the release of JS packages too, if that project should be in another repository or if it should be here either.

I am open to suggestions and contributions. :)

**Comment by sisimomo** [comment]
I just published a first version (0.0.1) of a simple little query builder for now. I will use it in my small project and improve it if I notice that it is missing some features. Any contribution is welcome. This is my first time publishing a bookseller so I am open to suggestions.

Here is the link:
https://github.com/sisimomo/Spring-Filter-Query-Builder

**Comment by torshid** [comment]
That looks great! It would be better if it's possible to do something _similar_ to `import static FilterBuilder.*;` in order to use the builder as in the example I have given initially. It would require some changes I think.

Example: `filter = equal("field", "value")`

Implementing a fluent syntax would be even better (it's a bit difficult to implement that with Java in the current state of things, but it may be easier in JS), so that `filter = and(a, b)` becomes `filter = a.and(b)`.

Thanks anyways, I wasn't expecting someone to get that much invested. :)

**Comment by sisimomo** [comment]
Good idea!

I just pushed version 0.3.0 which implements a much more elegant syntax as you proposed.

Example:

```
import { SpringFilterQueryBuilder as SFQB } from 'https://cdn.jsdelivr.net/npm/spring-filter-query-builder@0.3.0/src/index.min.js';

const filter =
    SFQB.or(
        SFQB.and(
            SFQB.equal("test.test1", "testvalue1"),
            SFQB.isNotNull("test.test2")
        ),
        SFQB.notEqual("test.test2", "testvalue2")
    );

const req = await fetch('http://api/person?filter=' + filter.toString());
```

Note that the prefix ```SFQB``` could be replace by anything.

**Comment by torshid** [comment]
That's cleaner. :)

I have added a section in the readme referring to your repository.

Thanks again!

**Comment by 68ociredef** [comment]
Hi folks! 
Two months ago I have realized an Angular library that implements a filter builder. 
It is written in typescript and utilize an fluent syntax. 
This is the npm link to it: 
_https://www.npmjs.com/package/spring-filter-ng._
I hope that it is utile :)

**Comment by torshid** [comment]
@68ociredef thanks. :)
