### ISSUE TITLE
Restriction for object fields

### ISSUE THREAD

**Issue by andrejs-sinkevics** [turkraft/spring-filter#85]
Can you please add functionality(annotation on field) for disabled or permission to search by one field or more fields

**Comment by torshid** [comment]
There are many different use cases related to permissions. One may want to enable filtering only on annotated fields, or enable all fields but disable annotated ones, possibly enable or disable according to the logged user's permissions, etc. It would be very hard to solve all of these requirements.

However, if you are using JPA, you can set the `FILTERING_AUTHORIZATION` field of the `ExpressionGeneratorParameters` class which will let you manually enable or disable filtering a field. I will think about a better generic solution but it should answer your needs for now.

Let's say that you have created your own `@DisableFiltering` annotation. You can then do something like:

```java
ExpressionGeneratorParameters.FILTERING_AUTHORIZATION = new BiFunction<Path<?>, Object, Boolean>() {
  @Override
  public Boolean apply(Path<?> field, Object payload) {
    if (field.getJavaType().isAnnotationPresent(DisableFiltering.class)) {
      return false;
    }
    return true;
  }
};
```

I didn't test it but I think you got the idea. Let me know if that's fine for you. We can also discuss other solutions. :)

**Comment by andrejs-sinkevics** [comment]
Thanks. I like solution. (@DisableFiltering annotation)
