### ISSUE TITLE
Pagination with DocumentExecutor

### ISSUE THREAD

**Issue by marcopag90** [turkraft/spring-filter#87]
The method
```default Page<T> findAll(@Nullable Document doc, Pageable pageable) ```
should return a PageImpl object with informations regarding pageable objects (count and page number).
In order to achieve this, the default implementation should be the following:

```
@Override
    default Page<T> findAll(Document doc, Pageable pageable) {
        final Query query = BsonGeneratorUtils.getQueryFromDocument(doc).with(pageable);
        final long count = getMongoOperations().count(query, getMetadata().getJavaType());
        final List<T> content = getMongoOperations().find(query, getMetadata().getJavaType());
        return new PageImpl<>(content, pageable, count);
    }
```
I tried and tested it, so it can be directly implemented.

**Comment by torshid** [comment]
Thanks @marcopag90, fixed in https://github.com/turkraft/spring-filter/releases/tag/1.0.5.
