### ISSUE TITLE
Problems with operator ~

### ISSUE THREAD

**Issue by glodepa** [turkraft/spring-filter#89]
Hi turkraft,
I have problems with the ~ operator. In particular, in the README it is written that _"the * character can also be used instead of % when using the ~ comparator"_ but it functions only with *.
Thank you.

**Comment by torshid** [comment]
Hi @glodepa 
Not sure I got you. You are not able to use `%`?

**Comment by torshid** [comment]
Do you still have the problem?

**Comment by glodepa** [comment]
> Do you still have the problem?

Hello turkraft, I solved it. Thank you very much!

**Comment by skamv** [comment]
> > Do you still have the problem?
> 
> Hello turkraft, I solved it. Thank you very much!

How did you solve it @glodepa ?

**Comment by torshid** [comment]
@skamv hi, what is the problem you are facing exactly?

**Comment by skamv** [comment]
Hi @torshid, with * it works fine. Using % returns unwanted/non-matching results

**Comment by torshid** [comment]
It may be due to encoding, that what the point of supporting `*`.
