### ISSUE TITLE
Define available operators for each entity separately

### ISSUE THREAD

**Issue by nyszilard** [turkraft/spring-filter#91]
Hi turkraft,

In some cases, I want to prohibit users from using advanced filtering features.
Is there any way to do it?
Is there any way to disable certain operators or set the available operators explicitly for the entities?

**Comment by torshid** [comment]
Hello @nyszilard

I invite you to read my answer in https://github.com/turkraft/spring-filter/issues/85 which may help you.
In summary, there is a simple way to allow or refuse a field being filtered. You can write your own logic based on the current user, the entity, etc.

The `payload` argument shown in #85 is null by default, but if you are using Spring you may intercept the `@Filter Specification<T>` when it's being injected, and set your own `payload` (the user, or session for example) which you will get back when the `FILTERING_AUTHORIZATION` method is triggered.

Example for intercepting/wrapping the `Specification`:
```java
@Configuration
public class AuthorizeFilteringFilterableFieldsOnly implements WebMvcConfigurer {
  @Override
  public void addArgumentResolvers(List<HandlerMethodArgumentResolver> argumentResolvers) {
    argumentResolvers.add(new SpecificationFilterArgumentResolverWrapper());
  }
}
```

```java
public class SpecificationFilterArgumentResolverWrapper implements HandlerMethodArgumentResolver {

  private static final SpecificationFilterArgumentResolver ORIGINAL_RESOLVER =
      new SpecificationFilterArgumentResolver();

  @Override
  public boolean supportsParameter(MethodParameter methodParameter) {
    return ORIGINAL_RESOLVER.supportsParameter(methodParameter);
  }

  @Override
  public Object resolveArgument(MethodParameter methodParameter, ModelAndViewContainer modelAndViewContainer,
      NativeWebRequest nativeWebRequest, WebDataBinderFactory webDataBinderFactory) throws Exception {

    FilterSpecification<?> resolved = (FilterSpecification<?>) ORIGINAL_RESOLVER.resolveArgument(methodParameter,
        modelAndViewContainer, nativeWebRequest, webDataBinderFactory);

    resolved.setPayload(YOU PAYLOAD HERE);

    return resolved;

  }
```

Feel free to ask if it's not clear enough. I am also open to (generic) ideas regarding permissions if you have any.

**Comment by torshid** [comment]
Hey @nyszilard 👋

Could you solve the issue?

**Comment by torshid** [comment]
Closing for now, feel free to reopen if needed.
